apiVersion: v1
items:

# Services:

# hej-verden-db
- apiVersion: v1
  kind: Service
  metadata:
    name: db
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      protocol: TCP
      targetPort: 55555
    selector:
      app: db

# hej-verden-words
- apiVersion: v1
  kind: Service
  metadata:
    name: words
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      protocol: TCP
      targetPort: 55555
    selector:
      app: words

# hej-verden-web, intern adresse
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: service-web
    name: web
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      protocol: TCP
      targetPort: 55555
    selector:
      app: web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

# hej-verden-web, 'ekstern' adresse
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: service-web-published
    name: web-published
  spec:
    clusterIP: 10.109.33.31
    externalTrafficPolicy: Cluster
    ports:
    - name: 8094-tcp
      nodePort: 31389
      port: 8094
      protocol: TCP
      targetPort: 80
    selector:
      app: web
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - hostname: localhost

# Deployments:

# hej-verden-db
- apiVersion: apps/v1
  kind: Deployment
  metadata:    
    name: backend-db
    namespace: default    
  spec:    
    replicas: 1    
    selector:
      matchLabels:
        app: db
    template:
      metadata:        
        labels:
          app: db
      spec:        
        containers:
        - image: dockersamples/k8s-wordsmith-db          
          name: db          
        dnsPolicy: ClusterFirst
        restartPolicy: Always  

# hej-verden-web
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-web
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: web        
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - image: dockersamples/k8s-wordsmith-web
          name: web
          ports:
          - containerPort: 80
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always

# hej-verden-words
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api-web
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: words
    template:
      metadata:
        labels:
          app: words
      spec:
        containers:
        - image: dockersamples/k8s-wordsmith-api
          name: words
          resources:
            limits:
              memory: "52428800"
            requests:
              memory: "52428800"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
kind: List