apiVersion: v1
items:

# Services:

# internal db service
- apiVersion: v1
  kind: Service
  metadata:
    name: db
  spec:
    clusterIP: None # Needs this or the service will not be created
    selector:
      app: db

# internal words service
- apiVersion: v1
  kind: Service
  metadata:
    name: words
  spec:
    clusterIP: None # Needs this or the service will not be created
    selector:
      app: words

# external web frontend service
- apiVersion: v1
  kind: Service
  metadata:
    name: web
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - port: 8094 # The external IP, e.g. http://localhost:8094/
      targetPort: 80 # The port the container is listening on for traffic
      protocol: TCP      
    selector:
      app: web
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - hostname: localhost

# Deployments:

# backend-db pod
- apiVersion: apps/v1
  kind: Deployment
  metadata:    
    name: backend-db
    namespace: default    
  spec:    
    replicas: 1    
    selector:
      matchLabels:
        app: db
    template:
      metadata:        
        labels:
          app: db
      spec:        
        containers:
        - image: dockersamples/k8s-wordsmith-db          
          name: db          
        dnsPolicy: ClusterFirst
        restartPolicy: Always  

# frontend-web pod
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-web
    namespace: default
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: web        
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - image: dockersamples/k8s-wordsmith-web
          name: web
        dnsPolicy: ClusterFirst
        restartPolicy: Always

# api-web pods
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api-web
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: words
    template:
      metadata:
        labels:
          app: words
      spec:
        containers:
        - image: dockersamples/k8s-wordsmith-api
          name: words
          resources:
            limits:
              memory: "52428800"
            requests:
              memory: "52428800"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
kind: List